### ISSUE TITLE
clarify whether Briss crops losslessly

### ISSUE THREAD

**Issue by jmtd** [mbaeuerle/Briss-2.0#35]
Documentation request: Does Briss crop losslessly? Put another way: are images embedded in PDF pages decoded and re-encoded/re-rastered (which, in the case of lossy images, would result in a potential quality degredation)? Thanks!

**Comment by mbaeuerle** [comment]
I can't really assure you that it's lossless as it is using some libs for this process. 
However from my current understanding it doesn't re-encode the content. 
It could even be the case that it doesn't remove the cropped parts at all but only changes which parts are visible.

**Comment by cleydyr** [comment]
From https://github.com/mbaeuerle/Briss-2.0/blob/1c628abd0e874e780ec75f2e5515f4239d3ddb85/src/main/java/at/laborg/briss/utils/DocumentCropper.java#L155 I'd guess the cropping is just an attribute added to the PDF file which determines the visible part of the document. So there's no actual encoding/decoding involved.

**Comment by cleydyr** [comment]
As the evidence so far shows that the crop is just an attribute that determines the visible part of the document, not implying any re-encoding of the media contained inside it, we can safely assume that the answer is "the crop rendering implementation is left to the readers according to the PDF specification instead of depending on Briss itself".

I'm closing this issue as answered.

Thanks
