### ISSUE TITLE
New crop rectangles are created behind older ones

### ISSUE THREAD

**Issue by mbaeuerle** [mbaeuerle/Briss-2.0#41]
When a new crop rectangle is created, it will be put behind the others. So when this rectangle is overlapping with an already existing one it cannot be selected. This is not intuitive and doesn't behave that way in other apps. 
It would make more sense that the new rect is put in front of the others. 
Maybe it even makes sense to add an option for moving a rect to the bottom / top.

**Comment by cleydyr** [comment]
Hey, @mbaeuerle .

I have some questions about this issues.

1. If the rectangle has just been created, the user should have been able to click on a free area of the page preview. Is that correct? If so, there's at least some area available to click on and select the recently-drawn rectangle.
2. If we add an option for moving a rectangle to bottom/top, then the user still has to be able to select the rectangle in the first place to view the available options. Is that correct? If so, then that solution is trying to solve a problem assuming that it doesn't exist beforehand.
3. If my understanding is incorrect, can you please clarify by providing steps to reproduce, expected behavior and current behavior in this issue?

Thank you

**Comment by mbaeuerle** [comment]
Hi @cleydyr,
1. Yes you are right. After creation one area of the rect will still be clickable, however if you create a smaller rectangle you can slide it under an older one resulting in a rectangle which is not clickable any longer. 
2. Also here you are correct, if you lost focus of the rectangle it is lost and you only can get it back by moving away the blocking ones. But if it is still selected moving to front should still be possible

Maybe these reasons do not justify adding "send to bottom / top" actions but I still think that adding new rectangles behind currently existing ones doesn't match user expectation. At least every app I know creates new objects in front of already existing ones.

**Comment by cleydyr** [comment]
Hey, @mbaeuerle . The simplest way to achieve that would be iterating on `crops` in reverse order when deciding what rectangle to delete or select, as the more recently a rectangle has been added, more in the end it is. Does it make sense to you?
